version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            database: default@test
            password: root
            rawAccess: true
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - myvolume:/var/lib/mysql
volumes:
  myvolume: ~
